# Generated by Django 3.2.7 on 2021-09-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsAndLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
