# Generated by Django 3.2.7 on 2021-09-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsandlikes',
            old_name='videoId',
            new_name='video_id',
        ),
    ]
