# Generated by Django 3.2.7 on 2021-09-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_videoid_commentsandlikes_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsandlikes',
            name='reply',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
